---
swagger: "2.0"
info:
  description: "This REST Api allows you to submit chemical identifiers in one format\
    \ and translate it into another format (e.g. SMILES -> InChi)"
  version: "1.0.0"
  title: "ChemIdConvert - Chemical identifier conversion service"
host: "chemidconvert"
basePath: "/v1"
schemes:
- "http"
produces:
- "application/json"
paths:
  /cas/to/inchi:
    get:
      tags:
      - "InChI, CAS"
      summary: "Converts from a CAS number into InChI format"
      description: "Converts from a CAS number into InChI. Only a single match is\
        \ returned if there is an ambiguity in the conversion. The conversion is performed\
        \ by using an external webservice and has relatively high latency.\n"
      operationId: "controllers.default_controller.cas_to_inchi_get"
      parameters:
      - name: "cas"
        in: "query"
        description: "Compound structure notated as a CAS number (3 groups of numbers\
          \ separated by dashes)"
        required: true
        type: "string"
        x-ontology: "http://edamontology.org/data_3102"
      responses:
        200:
          description: "The converted InChI string"
          schema:
            $ref: "#/definitions/inline_response_200"
        400:
          description: "Invalid request (typically a mandatory parameter was missing\
            \ or malformed)"
          schema:
            $ref: "#/definitions/simpleError"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/simpleError"
      x-tags:
      - tag: "InChI, CAS"
  /cas/to/inchikey:
    get:
      tags:
      - "InChiKey, CAS"
      summary: "Converts from a CAS number into InChIKey format"
      description: "Converts from a CAS number into InChIKey. Only a single match\
        \ is returned if there is an ambiguity in the conversion. The conversion is\
        \ performed by using an external webservice and has relatively high latency.\n"
      operationId: "controllers.default_controller.cas_to_inchikey_get"
      parameters:
      - name: "cas"
        in: "query"
        description: "Compound structure notated as a CAS number (3 groups of numbers\
          \ separated by dashes)"
        required: true
        type: "string"
        x-ontology: "http://edamontology.org/data_3102"
      responses:
        200:
          description: "The converted InChIKey string"
          schema:
            $ref: "#/definitions/inline_response_200_1"
        400:
          description: "Invalid request (typically a mandatory parameter was missing\
            \ or malformed)"
          schema:
            $ref: "#/definitions/simpleError"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/simpleError"
      x-tags:
      - tag: "InChiKey, CAS"
  /cas/to/smiles:
    get:
      tags:
      - "SMILES, CAS"
      summary: "Converts from a CAS number into (canonical) SMILES format"
      description: "Converts from a CAS number into (canonical) SMILES. Only a single\
        \ match is returned if there is an ambiguity in the conversion. The conversion\
        \ is performed by using an external webservice and has relatively high latency.\n"
      operationId: "controllers.default_controller.cas_to_smiles_get"
      parameters:
      - name: "cas"
        in: "query"
        description: "Compound structure notated as a CAS number (3 groups of numbers\
          \ separated by dashes)"
        required: true
        type: "string"
        x-ontology: "http://edamontology.org/data_3102"
      responses:
        200:
          description: "The converted SMILES string"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        400:
          description: "Invalid request (typically a mandatory parameter was missing\
            \ or malformed)"
          schema:
            $ref: "#/definitions/simpleError"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/simpleError"
      x-tags:
      - tag: "SMILES, CAS"
  /inchi/to/cas:
    get:
      tags:
      - "CAS, InChI"
      summary: "Converts from a InChI format into a CAS number"
      description: "Converts from a InChI format into a CAS number. Only a single\
        \ match is returned if there is an ambiguity in the conversion. The conversion\
        \ is performed by using an external webservice and has relatively high latency.\n"
      operationId: "controllers.default_controller.inchi_to_cas_get"
      parameters:
      - name: "inchi"
        in: "query"
        description: "Compound structure notated using InChI notation"
        required: true
        type: "string"
        x-ontology: "http://edamontology.org/format_1197"
      responses:
        200:
          description: "The converted CAS number (3 groups of numbers separated by\
            \ dashes)"
          schema:
            $ref: "#/definitions/inline_response_200_3"
        400:
          description: "Invalid request (typically a mandatory parameter was missing\
            \ or malformed)"
          schema:
            $ref: "#/definitions/simpleError"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/simpleError"
      x-tags:
      - tag: "CAS, InChI"
  /inchi/to/inchikey:
    get:
      tags:
      - "InChI, InChIKey"
      summary: "Converts from a InChI format into InChIKey format"
      description: "Converts from InChI format into InChIKey. The conversion is performed\
        \ in process via rdkit.\n"
      operationId: "controllers.default_controller.inchi_to_inchikey_get"
      parameters:
      - name: "inchi"
        in: "query"
        description: "Compound structure notated using InChI notation"
        required: true
        type: "string"
        x-ontology: "http://edamontology.org/format_1197"
      responses:
        200:
          description: "The converted InChIKey string"
          schema:
            $ref: "#/definitions/inline_response_200_1"
        400:
          description: "Invalid request (typically a mandatory parameter was missing\
            \ or malformed)"
          schema:
            $ref: "#/definitions/simpleError"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/simpleError"
      x-tags:
      - tag: "InChI, InChIKey"
  /inchi/to/smiles:
    get:
      tags:
      - "SMILES, InChI"
      summary: "Converts from a InChI format into (canonical) SMILES format"
      description: "Converts from InChI format into (canonical) SMILES. Only a single\
        \ match is returned if there is an ambiguity in the conversion. The conversion\
        \ is performed in process via rdkit.\n"
      operationId: "controllers.default_controller.inchi_to_smiles_get"
      parameters:
      - name: "inchi"
        in: "query"
        description: "Compound structure notated using InChI notation"
        required: true
        type: "string"
        x-ontology: "http://edamontology.org/format_1197"
      responses:
        200:
          description: "The converted SMILES string"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        400:
          description: "Invalid request (typically a mandatory parameter was missing\
            \ or malformed)"
          schema:
            $ref: "#/definitions/simpleError"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/simpleError"
      x-tags:
      - tag: "SMILES, InChI"
  /inchikey/to/cas:
    get:
      tags:
      - "CAS, InChIKey"
      summary: "Converts from a InChIKey format into a CAS number"
      description: "Converts from a InChIKey format into a CAS number. Only a single\
        \ match is returned if there is an ambiguity in the conversion. The conversion\
        \ is performed by using an external webservice and has relatively high latency.\n"
      operationId: "controllers.default_controller.inchikey_to_cas_get"
      parameters:
      - name: "inchikey"
        in: "query"
        description: "Compound structure notated using InChIKey notation"
        required: true
        type: "string"
        x-ontology: "http://edamontology.org/format_1199"
      responses:
        200:
          description: "The converted CAS number (3 groups of numbers separated by\
            \ dashes)"
          schema:
            $ref: "#/definitions/inline_response_200_3"
        400:
          description: "Invalid request (typically a mandatory parameter was missing\
            \ or malformed)"
          schema:
            $ref: "#/definitions/simpleError"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/simpleError"
      x-tags:
      - tag: "CAS, InChIKey"
  /inchikey/to/inchi:
    get:
      tags:
      - "InChI, InChIKey"
      summary: "Converts from a InChIKey format into InChI format"
      description: "Converts from InChIKey format into InChI. The conversion is performed\
        \ by using an external webservice and has relatively high latency.\n"
      operationId: "controllers.default_controller.inchikey_to_inchi_get"
      parameters:
      - name: "inchikey"
        in: "query"
        description: "Compound structure notated using InChIKey notation"
        required: true
        type: "string"
        x-ontology: "http://edamontology.org/format_1199"
      responses:
        200:
          description: "The converted InChI string"
          schema:
            $ref: "#/definitions/inline_response_200"
        400:
          description: "Invalid request (typically a mandatory parameter was missing\
            \ or malformed)"
          schema:
            $ref: "#/definitions/simpleError"
        504:
          description: "Upstream service timeout"
          schema:
            $ref: "#/definitions/simpleError"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/simpleError"
      x-tags:
      - tag: "InChI, InChIKey"
  /inchikey/to/smiles:
    get:
      tags:
      - "SMILES, InChIKey"
      summary: "Converts from a InChIKey format into (canonical) SMILES format"
      description: "Converts from InChIKey format into (canonical) SMILES. The conversion\
        \ is performed by using an external webservice and has relatively high latency.\n"
      operationId: "controllers.default_controller.inchikey_to_smiles_get"
      parameters:
      - name: "inchikey"
        in: "query"
        description: "Compound structure notated using InChIKey notation"
        required: true
        type: "string"
        x-ontology: "http://edamontology.org/format_1199"
      responses:
        200:
          description: "The converted SMILES string"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        400:
          description: "Invalid request (typically a mandatory parameter was missing\
            \ or malformed)"
          schema:
            $ref: "#/definitions/simpleError"
        504:
          description: "Upstream service timeout"
          schema:
            $ref: "#/definitions/simpleError"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/simpleError"
      x-tags:
      - tag: "SMILES, InChIKey"
  /smiles/to/cas:
    get:
      tags:
      - "SMILES, CAS"
      summary: "Converts from a SMILES format into a CAS number"
      description: "Converts from a SMILES format into a CAS number. Only a single\
        \ match is returned if there is an ambiguity in the conversion. The conversion\
        \ is performed by using an external webservice and has relatively high latency.\n"
      operationId: "controllers.default_controller.smiles_to_cas_get"
      parameters:
      - name: "smiles"
        in: "query"
        description: "Compound structure notated using SMILES notation"
        required: true
        type: "string"
        format: "smiles"
        x-ontology: "http://edamontology.org/format_1196"
      responses:
        200:
          description: "The converted CAS number (3 groups of numbers separated by\
            \ dashes)"
          schema:
            $ref: "#/definitions/inline_response_200_3"
        400:
          description: "Invalid request (typically a mandatory parameter was missing\
            \ or malformed)"
          schema:
            $ref: "#/definitions/simpleError"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/simpleError"
      x-tags:
      - tag: "SMILES, CAS"
  /smiles/to/inchi:
    get:
      tags:
      - "SMILES, InChI"
      summary: "Converts from a SMILES format into InChI format"
      description: "Converts from a SMILES format into InChI format. Only a single\
        \ match is returned if there is an ambiguity in the conversion. The conversion\
        \ is performed in process via rdkit.\n"
      operationId: "controllers.default_controller.smiles_to_inchi_get"
      parameters:
      - name: "smiles"
        in: "query"
        description: "Compound structure notated using SMILES notation"
        required: true
        type: "string"
        format: "smiles"
        x-ontology: "http://edamontology.org/format_1196"
      responses:
        200:
          description: "The converted InChI string"
          schema:
            $ref: "#/definitions/inline_response_200"
        400:
          description: "Invalid request (typically a mandatory parameter was missing\
            \ or malformed)"
          schema:
            $ref: "#/definitions/simpleError"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/simpleError"
      x-tags:
      - tag: "SMILES, InChI"
  /smiles/to/inchikey:
    get:
      tags:
      - "SMILES, InChIKey"
      summary: "Converts from a SMILES format into InChIKey format"
      description: "Converts from SMILES format into InChIKey. The conversion is performed\
        \ in process via rdkit.\n"
      operationId: "controllers.default_controller.smiles_to_inchikey_get"
      parameters:
      - name: "smiles"
        in: "query"
        description: "Compound structure notated using SMILES notation"
        required: true
        type: "string"
        format: "smiles"
        x-ontology: "http://edamontology.org/format_1196"
      responses:
        200:
          description: "The converted InChIKey string"
          schema:
            $ref: "#/definitions/inline_response_200_1"
        400:
          description: "Invalid request (typically a mandatory parameter was missing\
            \ or malformed)"
          schema:
            $ref: "#/definitions/simpleError"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/simpleError"
      x-tags:
      - tag: "SMILES, InChIKey"
definitions:
  simpleError:
    type: "object"
    properties:
      message:
        type: "string"
  inline_response_200:
    properties:
      inchi:
        type: "string"
        description: "Compound structure notated using InChI notation"
        x-ontology: "http://edamontology.org/format_1197"
  inline_response_200_1:
    properties:
      inchikey:
        type: "string"
        description: "Compound structure notated using InChIKey"
        x-ontology: "http://edamontology.org/format_1199"
  inline_response_200_2:
    properties:
      inchi:
        type: "string"
        description: "Compound structure notated using (canonical) SMILES notation"
        x-ontology: "http://edamontology.org/format_1196"
  inline_response_200_3:
    properties:
      cas:
        type: "string"
        description: "Compound structure notated using a CAS number"
        x-ontology: "http://edamontology.org/data_3102"
parameters:
  smiles:
    name: "smiles"
    in: "query"
    description: "Compound structure notated using SMILES notation"
    required: true
    type: "string"
    format: "smiles"
    x-ontology: "http://edamontology.org/format_1196"
  inchi:
    name: "inchi"
    in: "query"
    description: "Compound structure notated using InChI notation"
    required: true
    type: "string"
    x-ontology: "http://edamontology.org/format_1197"
  inchikey:
    name: "inchikey"
    in: "query"
    description: "Compound structure notated using InChIKey notation"
    required: true
    type: "string"
    x-ontology: "http://edamontology.org/format_1199"
  cas:
    name: "cas"
    in: "query"
    description: "Compound structure notated as a CAS number (3 groups of numbers\
      \ separated by dashes)"
    required: true
    type: "string"
    x-ontology: "http://edamontology.org/data_3102"
responses:
  inchi:
    description: "The converted InChI string"
    schema:
      $ref: "#/definitions/inline_response_200"
  smiles:
    description: "The converted SMILES string"
    schema:
      $ref: "#/definitions/inline_response_200_2"
  inchikey:
    description: "The converted InChIKey string"
    schema:
      $ref: "#/definitions/inline_response_200_1"
  cas:
    description: "The converted CAS number (3 groups of numbers separated by dashes)"
    schema:
      $ref: "#/definitions/inline_response_200_3"
