openapi: 3.0.0
x-orn-@id: 'https://chemidconvert/v2'
x-orn-@type: 'x-orn:Service'
servers:
  - url: 'https://chemidconvert/v2'
info:
  title: ChemIdConvert - Chemical identifier conversion service
  description: 'This REST Api allows you to submit chemical identifiers in one format and translate it into another format (e.g. SMILES -> InChi)'
  version: 1.0.0
paths:
  /molWeight:
    x-orn-@id: "https://chemidconvert/v2/molWeight"
    x-orn-@type: "x-orn:Prediction"
    x-orn:expects: "x-orn:Compound"
    x-orn:returns: "molecularMass"
    get:
      summary: Returns the molecular weight (calculated with rdkit)
      parameters:
        - smiles:
            name: smiles
            x-orn-@type: "x-orn:Smiles"
            in: query
            description: Compound structure notated using SMILES notation
            required: true
            schema:
              type: string
      responses:
        '200':
          molWeight:
            description: The molecular weight (caluclated with rdkit)
            content:
              application/json-ld:
                schema:
                  type: object
                  properties:
                    "@context":
                      type: object
                      description: The Json-LD context
                    "@id":
                      type: string
                      description: The Json-LD id of the prediction
                    "@type":
                      type: string
                      description: The Json-LD type of this value
                    smiles:
                      type: string
                      description: Compound structure notated using (canonical) SMILES notation
                      x-orn-ontology-term: 'http://edamontology.org/format_1196'
                    molWeight:
                      type: number
                      description: The molecular weight (caluclated with rdkit)
              application/json:
                schema:
                  type: object
                  x-orn:@context: "https://chemidconvert/v2/context.json"
                  properties:
                    "@id":
                      type: string
                      description: The Json-LD id of the prediction
                    "@type":
                      type: string
                      description: The Json-LD type of this value
                    smiles:
                      type: string
                      description: Compound structure notated using (canonical) SMILES notation
                    molWeight:
                      type: number
                      description: The molecular weight (caluclated with rdkit)
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: string
  /smiles/to/inchi:
    get:
      summary: Converts from a SMILES format into InChI format
      description: >
        Converts from a SMILES format into InChI format. Only a single match is
        returned if there is an ambiguity in the conversion. The conversion is
        performed in process via rdkit.
      tags:
        - 'SMILES, InChI'
      parameters:
        - smiles:
          name: smiles
          in: query
          description: Compound structure notated using SMILES notation
          required: true
          x-orn-@type: "x-orn:Smiles"
          schema:
            type: string
            format: smiles
      responses:
        '200':
          description: The converted InChI string
          content:
            application/json:
              schema:
                type: object
                properties:
                  inchi:
                    type: string
                    description: Compound structure notated using InChI notation
                    x-ontology: 'http://edamontology.org/format_1197'
        '400':
          description: Invalid request (typically a mandatory parameter was missing or malformed)
          content:
            application/json:
              schema:
                type: string
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: string
