# ChemIdConvert - Chemical identifier conversion service
swagger: '2.0'
x-orn-@id: 'https://chemidconvert/v2'
x-orn-@type: 'x-orn:Service'
info:
  title: ChemIdConvert - Chemical identifier conversion service
  description: This REST Api allows you to submit chemical identifiers in one format and translate it into another format (e.g. SMILES -> InChi)
  version: "1.0.0"
# the domain of the service - in our use-case somewhat nonsensical but mandatory
host: chemidconvert
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /v2
produces:
  - application/json
paths:
  /asSvg:
    x-orn-@id: "https://chemidconvert/v2/asSvg"
    x-orn-@type: "x-orn:Visualisation"
    x-orn:expects:
      x-orn-@id: "x-orn:Compound"
    x-orn:returns:
    - x-orn-@id: "x-orn:Compound"
    - x-orn-@id: "x-orn:Visualisation"
    get:
      summary: Returns an svg text of the given molecule
      produces:
        - image/svg+xml
      parameters:
        - $ref: "#/parameters/smiles"
        - name: width
          in: query
          type: integer
          description: SVG image width
          required: false
          default: 450
        - name: height
          in: query
          type: integer
          description: SVG image height
          required: false
          default: 450
      responses:
        200:
          description: Successfully created an svg represenatation
          schema:
            type: string
            description: The text representation of the svg of the molecule
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/simpleError'
  /molWeight:
    x-orn-@id: "https://chemidconvert/v2/molWeight"
    x-orn-@type: "x-orn:Prediction"
    x-orn:expects:
      x-orn-@id: "x-orn:Compound"
    x-orn:returns:
    - x-orn-@id: "x-orn:PredictedValue"
    - x-orn-@id: "x-dc:MolWeight"
    get:
      summary: Returns the molecular weight (calculated with rdkit)
      parameters:
        - $ref: "#/parameters/smiles"
      responses:
        200:
          $ref: "#/responses/molWeight"
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/simpleError'
  /smiles/to/inchi:
    x-orn-@id: "https://chemidconvert/v2/smiles/to/inchi"
    x-orn-@type: "x-orn:Conversion"
    x-orn:expects:
      x-orn-@id: "x-orn:Compound"
    x-orn:returns:
      x-orn-@id: "x-orn:Compound"
    get:
      summary: Converts from a SMILES format into InChI format
      description: >
        Converts from a SMILES format into InChI format. Only a single match is
        returned if there is an ambiguity in the conversion. The conversion is
        performed in process via rdkit.
      tags:
        - SMILES
        - InChI
      parameters:
        - $ref: "#/parameters/smiles"
      responses:
        200:
          $ref: "#/responses/inchi"
        400:
          description: Invalid request (typically a mandatory parameter was missing or malformed)
          schema:
            $ref: '#/definitions/simpleError'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/simpleError'
  /inchi/to/smiles:
    x-orn-@id: "https://chemidconvert/v2/inchi/to/smiles"
    x-orn-@type: "x-orn:Conversion"
    x-orn:expects:
      x-orn-@id: "x-orn:Compound"
    x-orn:returns:
      x-orn-@id: "x-orn:Compound"
    get:
      summary: Converts from a InChI format into (canonical) SMILES format
      description: >
        Converts from InChI format into (canonical) SMILES. Only a single match is
        returned if there is an ambiguity in the conversion. The conversion is
        performed in process via rdkit.
      tags:
        - SMILES
        - InChI
      parameters:
        - $ref: "#/parameters/inchi"
      responses:
        200:
          $ref: "#/responses/smiles"
        400:
          description: Invalid request (typically a mandatory parameter was missing or malformed)
          schema:
            $ref: '#/definitions/simpleError'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/simpleError'
  /inchi/to/inchikey:
    x-orn-@id: "https://chemidconvert/v2/inchi/to/inchikey"
    x-orn-@type: "x-orn:Conversion"
    x-orn:expects:
      x-orn-@id: "x-orn:Compound"
    x-orn:returns:
      x-orn-@id: "x-orn:Compound"
    get:
      summary: Converts from a InChI format into InChIKey format
      description: >
        Converts from InChI format into InChIKey. The conversion is
        performed in process via rdkit.
      tags:
        - InChI
        - InChIKey
      parameters:
        - $ref: "#/parameters/inchi"
      responses:
        200:
          $ref: "#/responses/inchikey"
        400:
          description: Invalid request (typically a mandatory parameter was missing or malformed)
          schema:
            $ref: '#/definitions/simpleError'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/simpleError'
  /inchikey/to/inchi:
    x-orn-@id: "https://chemidconvert/v2/inchikey/to/inchi"
    x-orn-@type: "x-orn:Conversion"
    x-orn:expects:
      x-orn-@id: "x-orn:Compound"
    x-orn:returns:
      x-orn-@id: "x-orn:Compound"
    get:
      summary: Converts from a InChIKey format into InChI format
      description: >
        Converts from InChIKey format into InChI. The conversion is
        performed by using an external webservice and has relatively high latency.
      tags:
        - InChI
        - InChIKey
      parameters:
        - $ref: "#/parameters/inchikey"
      responses:
        200:
          $ref: "#/responses/inchi"
        400:
          description: Invalid request (typically a mandatory parameter was missing or malformed)
          schema:
            $ref: '#/definitions/simpleError'
        500:
          description: Error in conversion by external webservice
          schema:
            $ref: '#/definitions/simpleError'
        504:
          description: Upstream service timeout
          schema:
            $ref: '#/definitions/simpleError'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/simpleError'
  /smiles/to/inchikey:
    x-orn-@id: "https://chemidconvert/v2/smiles/to/inchikey"
    x-orn-@type: "x-orn:Conversion"
    x-orn:expects:
      x-orn-@id: "x-orn:Compound"
    x-orn:returns:
      x-orn-@id: "x-orn:Compound"
    get:
      summary: Converts from a SMILES format into InChIKey format
      description: >
        Converts from SMILES format into InChIKey. The conversion is
        performed in process via rdkit.
      tags:
        - SMILES
        - InChIKey
      parameters:
        - $ref: "#/parameters/smiles"
      responses:
        200:
          $ref: "#/responses/inchikey"
        400:
          description: Invalid request (typically a mandatory parameter was missing or malformed)
          schema:
            $ref: '#/definitions/simpleError'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/simpleError'
  /inchikey/to/smiles:
    x-orn-@id: "https://chemidconvert/v2/inchikey/to/smiles"
    x-orn-@type: "x-orn:Conversion"
    x-orn:expects:
      x-orn-@id: "x-orn:Compound"
    x-orn:returns:
      x-orn-@id: "x-orn:Compound"
    get:
      summary: Converts from a InChIKey format into (canonical) SMILES format
      description: >
        Converts from InChIKey format into (canonical) SMILES. The conversion is
        performed by using an external webservice and has relatively high latency.
      tags:
        - SMILES
        - InChIKey
      parameters:
        - $ref: "#/parameters/inchikey"
      responses:
        200:
          $ref: "#/responses/smiles"
        400:
          description: Invalid request (typically a mandatory parameter was missing or malformed)
          schema:
            $ref: '#/definitions/simpleError'
        500:
          description: Error in conversion by external webservice
          schema:
            $ref: '#/definitions/simpleError'
        504:
          description: Upstream service timeout
          schema:
            $ref: '#/definitions/simpleError'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/simpleError'
  /smiles/to/cas:
    x-orn-@id: "https://chemidconvert/v2/smiles/to/cas"
    x-orn-@type: "x-orn:Conversion"
    x-orn:expects:
      x-orn-@id: "x-orn:Compound"
    x-orn:returns:
      x-orn-@id: "x-orn:Compound"
    get:
      summary: Converts from a SMILES format into a CAS number
      description: >
        Converts from a SMILES format into a CAS number. Only a single match is
        returned if there is an ambiguity in the conversion. The conversion is
        performed by using an external webservice and has relatively high latency.
      tags:
        - SMILES
        - CAS
      parameters:
        - $ref: "#/parameters/smiles"
      responses:
        200:
          $ref: "#/responses/cas"
        400:
          description: Invalid request (typically a mandatory parameter was missing or malformed)
          schema:
            $ref: '#/definitions/simpleError'
        500:
          description: Error in conversion by external webservice
          schema:
            $ref: '#/definitions/simpleError'
        504:
          description: Upstream service timeout
          schema:
            $ref: '#/definitions/simpleError'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/simpleError'
  /cas/to/smiles:
    x-orn-@id: "https://chemidconvert/v2/cas/to/smiles"
    x-orn-@type: "x-orn:Conversion"
    x-orn:expects:
      x-orn-@id: "x-orn:Compound"
    x-orn:returns:
      x-orn-@id: "x-orn:Compound"
    get:
      summary: Converts from a CAS number into (canonical) SMILES format
      description: >
        Converts from a CAS number into (canonical) SMILES. Only a single match is
        returned if there is an ambiguity in the conversion. The conversion is
        performed by using an external webservice and has relatively high latency.
      tags:
        - SMILES
        - CAS
      parameters:
        - $ref: "#/parameters/cas"
      responses:
        200:
          $ref: "#/responses/smiles"
        400:
          description: Invalid request (typically a mandatory parameter was missing or malformed)
          schema:
            $ref: '#/definitions/simpleError'
        500:
          description: Error in conversion by external webservice
          schema:
            $ref: '#/definitions/simpleError'
        504:
          description: Upstream service timeout
          schema:
            $ref: '#/definitions/simpleError'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/simpleError'
  /inchi/to/cas:
    x-orn-@id: "https://chemidconvert/v2/inchi/to/cas"
    x-orn-@type: "x-orn:Conversion"
    x-orn:expects:
      x-orn-@id: "x-orn:Compound"
    x-orn:returns:
      x-orn-@id: "x-orn:Compound"
    get:
      summary: Converts from a InChI format into a CAS number
      description: >
        Converts from a InChI format into a CAS number. Only a single match is
        returned if there is an ambiguity in the conversion. The conversion is
        performed by using an external webservice and has relatively high latency.
      tags:
        - CAS
        - InChI
      parameters:
        - $ref: "#/parameters/inchi"
      responses:
        200:
          $ref: "#/responses/cas"
        400:
          description: Invalid request (typically a mandatory parameter was missing or malformed)
          schema:
            $ref: '#/definitions/simpleError'
        500:
          description: Error in conversion by external webservice
          schema:
            $ref: '#/definitions/simpleError'
        504:
          description: Upstream service timeout
          schema:
            $ref: '#/definitions/simpleError'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/simpleError'
  /cas/to/inchi:
    x-orn-@id: "https://chemidconvert/v2/cas/to/inchi"
    x-orn-@type: "x-orn:Conversion"
    x-orn:expects:
      x-orn-@id: "x-orn:Compound"
    x-orn:returns:
      x-orn-@id: "x-orn:Compound"
    get:
      summary: Converts from a CAS number into InChI format
      description: >
        Converts from a CAS number into InChI. Only a single match is
        returned if there is an ambiguity in the conversion. The conversion is
        performed by using an external webservice and has relatively high latency.
      tags:
        - CAS
        - InChI
      parameters:
        - $ref: "#/parameters/cas"
      responses:
        200:
          $ref: "#/responses/inchi"
        400:
          description: Invalid request (typically a mandatory parameter was missing or malformed)
          schema:
            $ref: '#/definitions/simpleError'
        500:
          description: Error in conversion by external webservice
          schema:
            $ref: '#/definitions/simpleError'
        504:
          description: Upstream service timeout
          schema:
            $ref: '#/definitions/simpleError'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/simpleError'
  /inchikey/to/cas:
    x-orn-@id: "https://chemidconvert/v2/inchikey/to/cas"
    x-orn-@type: "x-orn:Conversion"
    x-orn:expects:
      x-orn-@id: "x-orn:Compound"
    x-orn:returns:
      x-orn-@id: "x-orn:Compound"
    get:
      summary: Converts from a InChIKey format into a CAS number
      description: >
        Converts from a InChIKey format into a CAS number. Only a single match is
        returned if there is an ambiguity in the conversion. The conversion is
        performed by using an external webservice and has relatively high latency.
      tags:
        - CAS
        - InChIKey
      parameters:
        - $ref: "#/parameters/inchikey"
      responses:
        200:
          $ref: "#/responses/cas"
        400:
          description: Invalid request (typically a mandatory parameter was missing or malformed)
          schema:
            $ref: '#/definitions/simpleError'
        500:
          description: Error in conversion by external webservice
          schema:
            $ref: '#/definitions/simpleError'
        504:
          description: Upstream service timeout
          schema:
            $ref: '#/definitions/simpleError'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/simpleError'
  /cas/to/inchikey:
    x-orn-@id: "https://chemidconvert/v2/cas/to/inchikey"
    x-orn-@type: "x-orn:Conversion"
    x-orn:expects:
      x-orn-@id: "x-orn:Compound"
    x-orn:returns:
      x-orn-@id: "x-orn:Compound"
    get:
      summary: Converts from a CAS number into InChIKey format
      description: >
        Converts from a CAS number into InChIKey. Only a single match is
        returned if there is an ambiguity in the conversion. The conversion is
        performed by using an external webservice and has relatively high latency.
      tags:
        - CAS
        - InChIKey
      parameters:
        - $ref: "#/parameters/cas"
      responses:
        200:
          $ref: "#/responses/inchikey"
        400:
          description: Invalid request (typically a mandatory parameter was missing or malformed)
          schema:
            $ref: '#/definitions/simpleError'
        500:
          description: Error in conversion by external webservice
          schema:
            $ref: '#/definitions/simpleError'
        504:
          description: Upstream service timeout
          schema:
            $ref: '#/definitions/simpleError'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/simpleError'
parameters:
  smiles:
    x-orn-@type: "x-orn:Smiles"
    name: smiles
    in: query
    type: string
    format: smiles
    description: Compound structure notated using SMILES notation
    required: true
  inchi:
    x-orn-@type: "x-orn:Inchi"
    name: inchi
    in: query
    type: string
    description: Compound structure notated using InChI notation
    required: true
  inchikey:
    x-orn-@type: "x-orn:InchiKey"
    name: inchikey
    in: query
    type: string
    description: Compound structure notated using InChIKey notation
    required: true
  cas:
    x-orn-@type: "x-orn:CasNumber"
    name: cas
    in: query
    type: string
    description: Compound structure notated as a CAS number (3 groups of numbers separated by dashes)
    required: true
responses:
  inchi:
    description: The converted InChI string
    schema:
      type: object
      properties:
        inchi:
          x-orn-@type: "x-orn:Inchi"
          type: string
          description: Compound structure notated using InChI notation
  smiles:
    description: The converted SMILES string
    schema:
      type: object
      properties:
        smiles:
          type: string
          x-orn-@type: "x-orn:Smiles"
          description: Compound structure notated using (canonical) SMILES notation
  inchikey:
    description: The converted InChIKey string
    schema:
      type: object
      properties:
        inchikey:
          type: string
          x-orn-@type: "x-orn:InchiKey"
          description: Compound structure notated using InChIKey
  cas:
    description: The converted CAS number (3 groups of numbers separated by dashes)
    schema:
      type: object
      properties:
        cas:
          type: string
          x-orn-@type: "x-orn:CasNumber"
          description: Compound structure notated using a CAS number
  molWeight:
    description: The molecular weight (caluclated with rdkit)
    schema:
      type: object
      properties:
        smiles:
          type: string
          x-orn-@type: "x-orn:Smiles"
          description: Compound structure notated using (canonical) SMILES notation
        molWeight:
          type: number
          x-orn-@type: "x-dc:MolWeight"
          description: The molecular weight (caluclated with rdkit)
definitions:
  simpleError:
    type: string
