# ChemIdConvert - Chemical identifier conversion service
swagger: '2.0'
info:
  title: ChemIdConvert - Chemical identifier conversion service
  description: This REST Api allows you to submit chemical identifiers in one format and translate it into another format (e.g. SMILES -> InChi)
  version: "1.0.0"
# the domain of the service - in our use-case somewhat nonsensical but mandatory
host: chemidconvert
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /smiles/toInchi:
    get:
      summary: Converts from a SMILES format into InChI format
      description: Converts from a SMILES format into InChI format
      tags:
        - SMILES, InChI
      parameters:
        - name: smiles
          in: query
          type: string
          description: Compound structure notated using SMILES notation
          required: true
          x-ontology: http://edamontology.org/format_1196
      responses:
        200:
          description: An array of rows
          schema:
            type: object
            properties:
              inchi:
                type: string
                description: Compound structure notated using InChI notation
                x-ontology: http://edamontology.org/format_1197
        default:
          description: Unexpected error
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              fields:
                type: string
